name = "ParametricMCPs"
uuid = "9b992ff8-05bb-4ea1-b9d2-5ef72d82f7ad"
authors = ["lassepe <lasse.peters@mailbox.org> and contributors"]
version = "0.1.16"

[deps]
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PATHSolver = "f5f7c340-0bb3-5c69-969a-41884d311d1b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
ChainRulesCoreExt = "ChainRulesCore"
ForwardDiffExt = "ForwardDiff"

[compat]
ChainRulesCore = "1"
FastDifferentiation = "0.4"
ForwardDiff = "0.10"
PATHSolver = "1.4"
Symbolics = "4,5,6"
julia = "1.10"
